SocialTracker\Bundle\ApplicationBundle\Entity\Instagram:
    type: entity
    repositoryClass: SocialTracker\Bundle\ApplicationBundle\Entity\InstagramRepository
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        instagram_id:
            type: string
        content:
            type: text
        created_time:
            type: integer

    manyToOne:
        user:
            targetEntity: User
            inversedBy: instagram_posts
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }