SocialTracker\Bundle\ApplicationBundle\Entity\User:
    type: entity
    repositoryClass: SocialTracker\Bundle\ApplicationBundle\Entity\UserRepository
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        instagram_access_token:
            type: string
            nullable: true
        instagram_username:
            type: string
            nullable: true
        instagram_max_id:
            type: string
            nullable: true

        facebook_access_token:
            type: text
            nullable: true
        facebook_username:
            type: string
            length: 255
            nullable: true
        facebook_last_post:
            type: integer
            nullable: true

        youtube_access_token:
            type: text
            nullable: true
        youtube_refresh_token:
            type: text
            nullable: true
        youtube_username:
            type: string
            length: 255
            nullable: true

        twitter_access_token:
            type: text
            nullable: true


    oneToMany:
        instagram_posts:
            targetEntity: InstagramPost
            mappedBy: user
        facebook_posts:
            targetEntity: FacebookPost
            mappedBy: user
        youtube_posts:
            targetEntity: YoutubePost
            mappedBy: user
    lifecycleCallbacks: {  }
