# - - - - - - - - - - #
# -   Application   - #
# - - - - - - - - - - #
application_home:
    path:   /
    defaults:  { _controller: SocialTrackerApplicationBundle:Application:home }

logout:
    path: /logout

register:
    path: /register

disable_social:
    path:   /social/{social}/disable
    defaults: { _controller: SocialTrackerApplicationBundle:Application:disableSocial }
    requirements:
        social: facebook|instagram|youtube

application_settings:
    path:   /settings
    defaults: { _controller: SocialTrackerApplicationBundle:Application:settings }

# API CALLBACK
settings_instagram_callback:
    path:   /settings/instagram_callback
    defaults: { _controller: SocialTrackerApplicationBundle:Application:instagramCallback }

settings_facebook_callback:
    path:   /settings/facebook_callback
    defaults: { _controller: SocialTrackerApplicationBundle:Application:facebookCallback }

settings_youtube_callback:
    path:   /settings/youtube_callback
    defaults: { _controller: SocialTrackerApplicationBundle:Application:youtubeCallback }


application_add_social:
    path:   /social/add
    defaults: { _controller: SocialTrackerApplicationBundle:Application:ajaxAddSocial }

application_remove_social:
    path:   /social/remove
    defaults: { _controller: SocialTrackerApplicationBundle:Application:ajaxRemoveSocial }

# - - - - - - - - - - #
# -       User      - #
# - - - - - - - - - - #

update_password:
    path:   /user/{id}/updatePassword
    defaults: { _controller: SocialTrackerApplicationBundle:User:updatePassword }
    requirements:
        id: \d+

login:
    path: /login
    defaults: { _controller: SocialTrackerApplicationBundle:User:login }

login_check:
    path: /login_check

# - - - - - - - - - - #
# -    Instagram    - #
# - - - - - - - - - - #
instagram_home:
    path:   /instagram
    defaults: { _controller: SocialTrackerApplicationBundle:Instagram:home }

instagram_refresh_media:
    path:   /instagram/{media}/refresh
    defaults: { _controller: SocialTrackerApplicationBundle:Instagram:refreshMedia }

instagram_delete_media:
    path:   /instagram/{id}/delete
    defaults: { _controller: SocialTrackerApplicationBundle:Instagram:deleteMedia }
    requirements:
        _method: DELETE

instagram_user_feed:
    path:   /instagram/feed/{maxId}
    defaults: { _controller: SocialTrackerApplicationBundle:Instagram:ajaxUserFeed }

instagram_media_show:
    path:   /instagram/{id}
    defaults: { _controller: SocialTrackerApplicationBundle:Instagram:showMedia }

instagram_media_like:
    path:   /instagram/{id}/like
    defaults: { _controller: SocialTrackerApplicationBundle:Instagram:ajaxLikeMedia }

instagram_media_dislike:
    path:   /instagram/{id}/dislike
    defaults: { _controller: SocialTrackerApplicationBundle:Instagram:ajaxDislikeMedia }

# - - - - - - - - - - #
# -    Facebook     - #
# - - - - - - - - - - #
facebook_home:
    path:   /facebook
    defaults: { _controller: SocialTrackerApplicationBundle:Facebook:home }

facebook_publish:
    path:   /facebook/publish
    defaults: { _controller: SocialTrackerApplicationBundle:Facebook:ajaxPublish }
    methods: POST

# - - - - - - - - - - #
# -     Youtube     - #
# - - - - - - - - - - #
youtube_home:
    path: /youtube
    defaults: { _controller: SocialTrackerApplicationBundle:Youtube:home }




