parameters:
    facebook_redirect_url: 'http://social-tracker.com/settings/facebook_callback'

services:
    # - - - - - - - - - - # 
    # -    Instagram    - #
    # - - - - - - - - - - #
    instagram:
        class: SocialTracker\Bundle\ApplicationBundle\Instagram\Instagram
        arguments:
            - @guzzle.client
            - @doctrine.orm.entity_manager

    instagram.authentication_helper:
        class: SocialTracker\Bundle\ApplicationBundle\Instagram\AuthenticationHelper
        arguments:
            - %instagram_client_id%
            - %instagram_secret%
            - @guzzle.client
            - @router

    # - - - - - - - - - - #
    # -    Facebook     - #
    # - - - - - - - - - - #
    facebook:
        class: SocialTracker\Bundle\ApplicationBundle\Facebook\Facebook
        arguments:
            - @facebook.authentication_helper

    facebook.authentication_helper:
        class: SocialTracker\Bundle\ApplicationBundle\Facebook\AuthenticationHelper
        arguments:
            - %facebook_client_id%
            - %facebook_secret%
            - @guzzle.client
            - @router
            - @facebook.login_helper

    facebook.login_helper:
        class: SocialTracker\Bundle\ApplicationBundle\Facebook\RedirectLoginHelper
        arguments:
            - @session
            - %facebook_redirect_url%
            - %facebook_client_id%
            - %facebook_secret%

    # - - - - - - - - - - #
    # -     Youtube     - #
    # - - - - - - - - - - #
    youtube:
        class: SocialTracker\Bundle\ApplicationBundle\Youtube\Youtube
        arguments:
            - @guzzle.client
            - @youtube.authentication_helper

    youtube.authentication_helper:
        class: SocialTracker\Bundle\ApplicationBundle\Youtube\AuthenticationHelper
        arguments: 
            - %youtube_client_id%
            - %youtube_secret%
            - @guzzle.client
            - @router

    twofactor.interactive_login_listener:
        class: SocialTracker\Bundle\ApplicationBundle\Security\InteractiveLoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    twofactor.request_listener:
        class: SocialTracker\Bundle\ApplicationBundle\Security\RequestListener
        arguments:
            - @router
            - @security.context
            - @templating
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onCoreRequest, priority: -1 }